/*
* generated by Xtext
*/
package de.ckl.xtext.tycho.ui.contentassist;

import de.ckl.xtext.tycho.ui.contentassist.AbstractTychoProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TychoProposalProvider extends AbstractTychoProposalProvider {

}
