/*
* generated by Xtext
*/
package de.ckl.xtext.tycho.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class TychoOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
