/*
 * generated by Xtext
 */
package de.ckl.xtext.tycho;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TychoRuntimeModule extends de.ckl.xtext.tycho.AbstractTychoRuntimeModule {

}
