/*
 * generated by Xtext
 */
package de.ckl.xtext.tycho.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TychoUiModule extends de.ckl.xtext.tycho.ui.AbstractTychoUiModule {
	public TychoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
